"use client";

import { create } from "zustand";
import type { Artifact } from "@/lib/models/types";

/**
 * Artifacts — durable files uploaded by the user or generated by the
 * agent, associated with conversations and reviewable in a dedicated area.
 * The server (/api/artifacts) is the source of truth; every mutation is
 * mirrored with fire-and-forget requests.
 */
interface ArtifactsStore {
  artifacts: Artifact[];
  /** True once artifacts have been loaded from the server. */
  hydrated: boolean;

  hydrateFromServer: () => Promise<void>;
  addArtifact: (artifact: Omit<Artifact, "id" | "createdAt">) => Artifact;
  addArtifacts: (
    artifacts: Array<Omit<Artifact, "id" | "createdAt">>,
  ) => Artifact[];
  removeArtifact: (id: string) => void;
  artifactsForConversation: (conversationId: string) => Artifact[];
}

/** Double-invoke guard for hydrateFromServer(). */
let hydratePromise: Promise<void> | null = null;

function upsertOnServer(artifact: Artifact) {
  void fetch("/api/artifacts", {
    method: "PUT",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ artifact }),
  }).catch(() => {});
}

function deleteOnServer(id: string) {
  void fetch(`/api/artifacts?id=${encodeURIComponent(id)}`, {
    method: "DELETE",
  }).catch(() => {});
}

export const useArtifactsStore = create<ArtifactsStore>()((set, get) => ({
  artifacts: [],
  hydrated: false,

  hydrateFromServer: () => {
    if (get().hydrated) return Promise.resolve();
    if (hydratePromise) return hydratePromise;

    hydratePromise = (async () => {
      try {
        const resp = await fetch("/api/artifacts");
        if (!resp.ok) return;
        const json = (await resp.json()) as { artifacts?: Artifact[] };
        const docs = Array.isArray(json?.artifacts) ? json.artifacts : [];
        set({ artifacts: docs, hydrated: true });
      } catch {
        // Offline-tolerant: keep local state; a reload retries.
      } finally {
        hydratePromise = null;
      }
    })();
    return hydratePromise;
  },

  addArtifact: (artifact) => {
    const full: Artifact = {
      ...artifact,
      id: `art-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      createdAt: Date.now(),
    };
    set((s) => ({ artifacts: [full, ...s.artifacts] }));
    upsertOnServer(full);
    return full;
  },

  addArtifacts: (list) => {
    const full = list.map((a, i) => ({
      ...a,
      id: `art-${Date.now()}-${i}-${Math.random().toString(36).slice(2, 8)}`,
      createdAt: Date.now() + i,
    }));
    set((s) => ({ artifacts: [...full, ...s.artifacts] }));
    for (const artifact of full) upsertOnServer(artifact);
    return full;
  },

  removeArtifact: (id) => {
    set((s) => ({ artifacts: s.artifacts.filter((a) => a.id !== id) }));
    deleteOnServer(id);
  },

  artifactsForConversation: (conversationId) =>
    get().artifacts.filter((a) => a.conversationId === conversationId),
}));
