allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.ember.legacy'
    compileSdkVersion 34
    buildToolsVersion "34.0.0"

    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.ember.legacy"
        minSdkVersion 9
        targetSdkVersion 10
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }
}
