"use client";

import { useMemo, useState } from "react";
import { toast } from "sonner";
import {
  Boxes,
  Download,
  Eye,
  FileCode2,
  FileJson,
  FileText,
  FileUp,
  ImageIcon,
  MessageSquare,
  Sparkles,
  Trash2,
  Upload,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import type { Artifact } from "@/lib/models/types";
import { useArtifactsStore } from "@/store/artifacts-store";
import { useUIStore } from "@/store/ui-store";
import { useChatStore } from "@/store/chat-store";
import { MobileNavButton } from "../MobileNavButton";
import { formatBytes } from "../Composer";

function kindIcon(kind: Artifact["kind"]) {
  switch (kind) {
    case "image":
      return ImageIcon;
    case "pdf":
      return FileUp;
    case "code":
      return FileCode2;
    case "data":
      return FileJson;
    default:
      return FileText;
  }
}

function downloadArtifact(artifact: Artifact) {
  const a = document.createElement("a");
  if (artifact.dataUrl) {
    a.href = artifact.dataUrl;
  } else if (artifact.textContent) {
    const blob = new Blob([artifact.textContent], {
      type: artifact.mime || "text/plain",
    });
    a.href = URL.createObjectURL(blob);
  } else {
    toast.info("Preview not available", {
      description: `${artifact.name} is a mock binary — download arrives with real storage.`,
    });
    return;
  }
  a.download = artifact.name;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

/* ------------------------------------------------------------------ */
/* Preview dialog                                                      */
/* ------------------------------------------------------------------ */

export function ArtifactPreviewDialog() {
  const artifactPreviewId = useUIStore((s) => s.artifactPreviewId);
  const setArtifactPreviewId = useUIStore((s) => s.setArtifactPreviewId);
  const artifact = useArtifactsStore((s) =>
    s.artifacts.find((a) => a.id === artifactPreviewId),
  );
  const removeArtifact = useArtifactsStore((s) => s.removeArtifact);

  const open = Boolean(artifact);

  return (
    <Dialog open={open} onOpenChange={(o) => !o && setArtifactPreviewId(null)}>
      <DialogContent className="sm:max-w-lg">
        {artifact && (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2.5 text-base">
                <span className="flex size-8 items-center justify-center rounded-lg bg-secondary text-muted-foreground">
                  {(() => {
                    const Icon = kindIcon(artifact.kind);
                    return <Icon className="size-4" />;
                  })()}
                </span>
                <span className="min-w-0">
                  <span className="block truncate">{artifact.name}</span>
                  <span className="mt-0.5 block text-[11.5px] font-normal text-muted-foreground">
                    {artifact.kind.toUpperCase()} · {formatBytes(artifact.size)} ·{" "}
                    {artifact.origin === "user" ? "Uploaded by you" : "Generated by agent"}
                    {artifact.conversationTitle
                      ? ` · in ${artifact.conversationTitle}`
                      : ""}
                  </span>
                </span>
              </DialogTitle>
              <DialogDescription className="sr-only">
                Preview of {artifact.name}
              </DialogDescription>
            </DialogHeader>

            <div className="scrollbar-thin max-h-[50vh] min-h-32 overflow-auto rounded-xl border border-border/60 bg-secondary/25 p-3">
              {artifact.dataUrl ? (
                <img
                  src={artifact.dataUrl}
                  alt={artifact.name}
                  className="mx-auto max-h-[46vh] rounded-lg object-contain"
                />
              ) : artifact.textContent ? (
                <pre className="whitespace-pre-wrap break-words font-mono text-[12px] leading-relaxed text-muted-foreground">
                  {artifact.textContent.slice(0, 10_000)}
                  {artifact.textContent.length > 10_000 && "\n\n… (truncated preview)"}
                </pre>
              ) : (
                <div className="flex h-36 flex-col items-center justify-center gap-2 text-center">
                  {(() => {
                    const Icon = kindIcon(artifact.kind);
                    return <Icon className="size-7 text-muted-foreground/50" />;
                  })()}
                  <p className="text-[12.5px] text-muted-foreground">
                    In-app preview for {artifact.kind.toUpperCase()} files is
                    coming soon.
                  </p>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="h-8 gap-1.5 text-[12.5px] text-destructive hover:bg-destructive/10 hover:text-destructive"
                onClick={() => {
                  removeArtifact(artifact.id);
                  setArtifactPreviewId(null);
                  toast.success("Artifact removed");
                }}
              >
                <Trash2 className="size-3.5" /> Remove
              </Button>
              <Button
                size="sm"
                className="h-8 gap-1.5 rounded-full px-4 text-[12.5px]"
                onClick={() => downloadArtifact(artifact)}
              >
                <Download className="size-3.5" /> Download
              </Button>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

/* ------------------------------------------------------------------ */
/* Artifacts view                                                      */
/* ------------------------------------------------------------------ */

type Filter = "all" | "user" | "agent";

export function ArtifactsView() {
  const artifacts = useArtifactsStore((s) => s.artifacts);
  const removeArtifact = useArtifactsStore((s) => s.removeArtifact);
  const setArtifactPreviewId = useUIStore((s) => s.setArtifactPreviewId);
  const openChat = useChatStore((s) => s.openChat);
  const [filter, setFilter] = useState<Filter>("all");

  const filtered = useMemo(
    () =>
      artifacts
        .filter((a) => filter === "all" || a.origin === filter)
        .sort((a, b) => b.createdAt - a.createdAt),
    [artifacts, filter],
  );

  const counts = useMemo(
    () => ({
      all: artifacts.length,
      user: artifacts.filter((a) => a.origin === "user").length,
      agent: artifacts.filter((a) => a.origin === "agent").length,
    }),
    [artifacts],
  );

  return (
    <div className="scrollbar-thin min-h-0 flex-1 overflow-y-auto">
      <div className="mx-auto max-w-3xl px-4 py-6 sm:px-6">
        <header className="mb-6 flex items-start gap-2">
          <MobileNavButton />
          <div>
            <h1 className="flex items-center gap-2.5 text-xl font-semibold">
              <Boxes className="size-5 text-primary" /> Artifacts
            </h1>
            <p className="mt-1.5 text-[13.5px] leading-relaxed text-muted-foreground">
              Files you&apos;ve uploaded and files the agent has generated — all
              reviewable in one place, across your chats.
            </p>
          </div>
        </header>

        {/* Filters */}
        <div className="mb-4 flex items-center gap-1.5">
          {(
            [
              ["all", "All", counts.all],
              ["user", "Uploaded", counts.user],
              ["agent", "Generated", counts.agent],
            ] as Array<[Filter, string, number]>
          ).map(([key, label, count]) => (
            <button
              key={key}
              onClick={() => setFilter(key)}
              aria-pressed={filter === key}
              className={cn(
                "flex h-8 items-center gap-1.5 rounded-full px-3.5 text-[12.5px] font-medium transition-colors",
                filter === key
                  ? "bg-primary/12 text-primary"
                  : "text-muted-foreground hover:bg-secondary hover:text-foreground",
              )}
            >
              {label}
              <span className="text-[11px] opacity-70">{count}</span>
            </button>
          ))}
        </div>

        {/* List */}
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center gap-3 rounded-2xl border border-dashed border-border px-6 py-14 text-center">
            <span className="flex size-11 items-center justify-center rounded-xl bg-secondary text-muted-foreground">
              <Boxes className="size-5" />
            </span>
            <div>
              <p className="text-[14px] font-medium">
                {filter === "all"
                  ? "No artifacts yet"
                  : filter === "user"
                    ? "No uploaded files yet"
                    : "No generated files yet"}
              </p>
              <p className="mx-auto mt-1 max-w-sm text-[12.5px] leading-relaxed text-muted-foreground">
                Attach files in the composer, paste large text as a file, or ask
                the agent to produce a report — everything lands here.
              </p>
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {filtered.map((a) => {
              const Icon = kindIcon(a.kind);
              return (
                <div
                  key={a.id}
                  className="group flex items-center gap-3 rounded-xl border border-border/60 bg-card px-3.5 py-3 transition-all hover:border-border"
                >
                  <span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-secondary text-muted-foreground">
                    {a.dataUrl ? (
                      <img
                        src={a.dataUrl}
                        alt=""
                        className="size-9 rounded-lg object-cover"
                      />
                    ) : (
                      <Icon className="size-4" />
                    )}
                  </span>

                  <div className="min-w-0 flex-1 leading-tight">
                    <div className="flex items-center gap-2">
                      <span className="truncate text-[13.5px] font-medium">
                        {a.name}
                      </span>
                      <span
                        className={cn(
                          "flex shrink-0 items-center gap-1 rounded-full px-1.5 py-0.5 text-[9.5px] font-semibold uppercase tracking-wide",
                          a.origin === "user"
                            ? "bg-secondary text-muted-foreground"
                            : "bg-primary/12 text-primary",
                        )}
                      >
                        {a.origin === "user" ? (
                          <Upload className="size-2.5" />
                        ) : (
                          <Sparkles className="size-2.5" />
                        )}
                        {a.origin === "user" ? "Uploaded" : "Generated"}
                      </span>
                    </div>
                    <div className="mt-0.5 flex items-center gap-1.5 text-[11.5px] text-muted-foreground">
                      {a.kind.toUpperCase()} · {formatBytes(a.size)}
                      {a.conversationTitle && (
                        <>
                          <span aria-hidden>·</span>
                          <button
                            className="flex items-center gap-1 truncate hover:text-foreground hover:underline"
                            onClick={() => {
                              if (a.conversationId) {
                                openChat(a.conversationId);
                                useUIStore.getState().goToChat();
                              }
                            }}
                          >
                            <MessageSquare className="size-2.5 shrink-0" />
                            <span className="truncate">{a.conversationTitle}</span>
                          </button>
                        </>
                      )}
                    </div>
                  </div>

                  <div className="flex shrink-0 items-center gap-0.5">
                    <button
                      aria-label={`Preview ${a.name}`}
                      onClick={() => setArtifactPreviewId(a.id)}
                      className="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
                    >
                      <Eye className="size-4" />
                    </button>
                    <button
                      aria-label={`Download ${a.name}`}
                      onClick={() => downloadArtifact(a)}
                      className="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
                    >
                      <Download className="size-4" />
                    </button>
                    <button
                      aria-label={`Remove ${a.name}`}
                      onClick={() => {
                        removeArtifact(a.id);
                        toast.success("Artifact removed");
                      }}
                      className="rounded-lg p-2 text-muted-foreground opacity-0 transition-all hover:bg-destructive/10 hover:text-destructive group-hover:opacity-100"
                    >
                      <Trash2 className="size-4" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
